#ifndef CHAR_CODES
#define CHAR_CODES

enum {
    ONE_BOMB = 0,
    TWO_BOMBS = 1,
    THREE_BOMBS = 2,
    FOUR_BOMBS = 3,
    FIVE_BOMBS = 4,
    SIX_BOMBS = 5,
    SEVEN_BOMBS = 6,
    EIGHT_BOMBS = 7,
    BLANK = 8,
    BOMB = 12,
    FLAG = 13,
    QUESTION_MARK = 14,
    CURSOR = 15,
    MINEFIELD_CORNER_TOP_LEFT = 24,
    MINEFIELD_TOP_TEE = 25,
    MINEFIELD_HORIZONTAL = 26,
    MINEFIELD_CORNER_TOP_RIGHT = 28,
    MINEFIELD_LEFT_TEE = 36,
    MINEFIELD_CROSS = 37,
    CLOSED_CELL = 50,
    MINEFIELD_RIGHT_TEE = 40,
    MINEFIELD_VERTICAL = 48,
    MINEFIELD_CORNER_BOTTOM_LEFT = 60,
    MINEFIELD_BOTTOM_TEE = 61,
    MINEFIELD_CORNER_BOTTOM_RIGHT = 64,
};

#endif /* CHAR_CODES */
