#ifndef COLORS_H
#define COLORS_H

enum {
    ONE_BOMB_COLOR = 1,
    TWO_BOMBS_COLOR = 2,
    THREE_BOMBS_COLOR = 3,
    FOUR_BOMBS_COLOR = 4,
    FIVE_BOMBS_COLOR = 5,
    SIX_BOMBS_COLOR = 6,
    SEVEN_BOMBS_COLOR = 7,
    EIGHT_BOMBS_COLOR = 8,
    UNCOVERED_BOMB_COLOR,
    EXPLODING_BOMB_COLOR,
    MINEFIELD_GRID_COLOR,
    TEXT_COLOR,
    BLANK_CELL_COLOR,
    CLOSED_CELL_COLOR,
    FLAG_COLOR,
    EMPTY_FLAG_COLOR,
    QUESTION_MARK_COLOR
};

#endif /* COLORS_H */
