name: Build workflow

on:
  workflow_call:
    outputs:
      prerelease:
        description: "Whether a prerelease artifact will be generated"
        value: ${{ jobs.build.outputs.prerelease }}
      draft:
        description: "Whether a draft artifact will be generated"
        value: ${{ jobs.build.outputs.draft }}

env:
  package_origin: github

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      prerelease: ${{ steps.get-version.outputs.prerelease }}
      draft: ${{ steps.get-version.outputs.draft }}
      file: ${{ steps.get-version.outputs.file }}
    container:
      image: ${{ matrix.image }}
      options: --user=root
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: docker://pvmm/sdcc:latest
            platform: msx2
          - image: docker://pvmm/ia16:python3
            platform: msdos
          - image: docker://pvmm/opengl:latest
            platform: opengl
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Compile repository code
      run: |
        cd platforms/${{ matrix.platform }}
        make
    - name: Determine release version and target directory name
      id: get-version
      run: |
        if [ '${{ github.event_name }}' = 'pull_request' ]; then
          draft='true'
          prerelease='false'
        else
          if echo "${{ github.ref_name }}" | grep -Eq 'rc[0-9]?$'; then
            draft='true'
            prerelease='true'
          elif echo "${{ github.ref_name }}" | grep -Eq '^v[0-9]'; then
              draft='false'
              prerelease='false'
          else
              draft='true'
              prerelease='false'
          fi
        fi
        echo "::set-output name=draft::$draft"
        echo "draft=$draft"
        echo "::set-output name=prerelease::$prerelease"
        echo "prerelease=$prerelease"
    - name: Upload redistributable package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: |
          platforms/${{ matrix.platform }}/build/
